### ISSUE TITLE
Typo: replace "mnv" with "mvn"

### ISSUE THREAD

**Issue by jamesjer** [fedora-java/howto#10]
There is one place in the document that refers to "%mnv_alias" instead of "%mvn_alias", in Section 7.1, Packaging Maven project

**Comment by mizdebsk** [comment]
Fixed, thanks!

**Comment by bhamail** [comment]
FWIW, this fix does not appear to have been published. 
See: https://fedora-java.github.io/howto/latest/#packaging_maven_project
Section:
"Add alias to Maven artifact"

still shows:

Add alias to Maven artifact
%mnv_alias org.example:simplemaven simplemaven:simplemaven

**Comment by mizdebsk** [comment]
> FWIW, this fix does not appear to have been published.

That's because currently site build is broken. @terminus-brut is working towards fixing it.
